"""Ability cooldowns and play notes. Patch-dependent; Season 4 typical values."""

# Maps English ability name -> cooldown string
HERO_CDS = {
    "ana": {"Sleep Dart": "14s", "Biotic Grenade": "12s", "Nano Boost": "ULT"},
    "anran": {"Fan the Flames": "8s", "Inferno Rush": "10s", "Dancing Blaze": "12s", "Vermillion Ascent": "ULT"},
    "ashe": {"Coach Gun": "10s", "Dynamite": "12s", "B.O.B.": "ULT"},
    "baptiste": {"Regenerative Burst": "15s", "Immortality Field": "25s", "Amplification Matrix": "ULT"},
    "bastion": {"A-36 Tactical Grenade": "8s", "Configuration: Assault": "12s", "Configuration: Artillery": "ULT"},
    "brigitte": {"Repair Pack": "1.5s/charge", "Whip Shot": "4s", "Shield Bash": "5s", "Rally": "ULT"},
    "cassidy": {"Combat Roll": "6s", "Magnetic Grenade": "10s", "Deadeye": "ULT"},
    "dmon": {"Surging Strike": "6s", "Fusion Repeater": "8s", "Propulsors": "fuel", "Limit Break": "ULT"},
    "domina": {"Barrier Array": "12s", "Crystal Charge": "8s", "Sonic Repulsors": "10s", "Panopticon": "ULT"},
    "doomfist": {"Rocket Punch": "3.5s", "Seismic Slam": "6s", "Power Block": "resource", "Meteor Strike": "ULT"},
    "dva": {"Boosters": "3.5s", "Defense Matrix": "resource", "Micro Missiles": "8s", "Self-Destruct": "ULT"},
    "echo": {"Sticky Bombs": "6s", "Flight": "6s", "Focusing Beam": "8s", "Duplicate": "ULT"},
    "emre": {"Cyber Frag": "8s", "Siphon Blaster": "weapon", "Override Protocol": "ULT"},
    "freja": {"Quick Dash": "6s", "Updraft": "8s", "Take Aim": "refresh", "Bola Shot": "ULT"},
    "genji": {"Deflect": "8s", "Swift Strike": "8s", "Dragonblade": "ULT"},
    "hanzo": {"Storm Arrows": "10s", "Sonic Arrow": "12s", "Lunge": "5s", "Dragonstrike": "ULT"},
    "hazard": {"Spike Guard": "resource", "Jagged Wall": "12s", "Violent Leap": "6s", "Downpour": "ULT"},
    "illari": {"Outburst": "7s", "Healing Pylon": "16s", "Captive Sun": "ULT"},
    "jetpack-cat": {"Lifeline": "10s", "Frenetic Flight": "fuel", "Purr": "14s", "Catnapper": "ULT"},
    "junker-queen": {"Jagged Blade": "6s", "Commanding Shout": "11s", "Carnage": "7s", "Rampage": "ULT"},
    "junkrat": {"Concussion Mine": "8s", "Steel Trap": "10s", "RIP-Tire": "ULT"},
    "juno": {"Pulsar Torpedoes": "10s", "Hyper Ring": "14s", "Glide Boost": "6.5s", "Orbital Ray": "ULT"},
    "kiriko": {"Swift Step": "7s", "Protection Suzu": "14s", "Kitsune Rush": "ULT"},
    "lifeweaver": {"Petal Platform": "12s", "Rejuvenating Dash": "5s", "Life Grip": "19s", "Tree of Life": "ULT"},
    "lucio": {"Soundwave": "5s", "Amp It Up": "12s", "Sound Barrier": "ULT"},
    "mauga": {"Overrun": "6s", "Cardiac Overdrive": "12s", "Cage Fight": "ULT"},
    "mei": {"Cryo-Freeze": "12s", "Ice Wall": "12s", "Blizzard": "ULT"},
    "mercy": {"Resurrect": "30s", "Guardian Angel": "no CD", "Valkyrie": "ULT"},
    "mizuki": {"Healing Kasa": "8s", "Katashiro Return": "12s", "Binding Chain": "10s", "Kekkai Sanctuary": "ULT"},
    "moira": {"Biotic Orb": "8s", "Fade": "6s", "Coalescence": "ULT"},
    "orisa": {"Energy Javelin": "6s", "Fortify": "16s", "Javelin Spin": "8s", "Terra Surge": "ULT"},
    "pharah": {"Jump Jet": "10s", "Concussive Blast": "7s", "Jet Dash": "8s", "Barrage": "ULT"},
    "ramattra": {"Void Barrier": "13s", "Nemesis Form": "8s", "Ravenous Vortex": "12s", "Annihilation": "ULT"},
    "reaper": {"Wraith Form": "8s", "Shadow Step": "10s", "Death Blossom": "ULT"},
    "reinhardt": {"Charge": "7s", "Fire Strike": "6s", "Barrier Field": "hold", "Earthshatter": "ULT"},
    "roadhog": {"Chain Hook": "8s", "Take a Breather": "8s", "Whole Hog": "ULT"},
    "shion": {"Evade": "6s", "Joyride": "10s", "Execution": "8s", "Satsuriku Spree": "ULT"},
    "sierra": {"Tracking Shot": "10s", "Anchor Drone": "8s", "Tremor Grenade": "8s", "Trailblazer": "ULT"},
    "sigma": {"Kinetic Grasp": "12s", "Accretion": "10s", "Experimental Barrier": "2s recast", "Gravitic Flux": "ULT"},
    "sojourn": {"Power Slide": "7s", "Disruptor Shot": "8s", "Overclock": "ULT"},
    "soldier-76": {"Sprint": "no CD", "Biotic Field": "15s", "Helix Rockets": "6s", "Tactical Visor": "ULT"},
    "sombra": {"Hack": "4s", "Translocator": "6s", "Stealth": "no CD", "EMP": "ULT"},
    "symmetra": {"Sentry Turret": "10s", "Teleporter": "12s", "Photon Barrier": "ULT"},
    "torbjorn": {"Deploy Turret": "10s", "Overload": "12s", "Molten Core": "ULT"},
    "tracer": {"Blink": "3s/charge ×3", "Recall": "12s", "Pulse Bomb": "ULT"},
    "vendetta": {"Whirlwind Slash": "7s", "Soaring Slice": "8s", "Warding Stance": "resource", "Sundering Blade": "ULT"},
    "venture": {"Drill Dash": "8s", "Burrow": "8s", "Tectonic Shock": "ULT"},
    "widowmaker": {"Grappling Hook": "12s", "Venom Mine": "15s", "Infra-Sight": "ULT"},
    "winston": {"Jump Pack": "5s", "Barrier Projector": "13s", "Primal Rage": "ULT"},
    "wrecking-ball": {"Piledriver": "10s", "Adaptive Shield": "15s", "Grappling Claw": "5s", "Minefield": "ULT"},
    "wuyang": {"Rushing Torrent": "6s", "Tidal Blast": "12s", "Guardian Blast": "ULT"},
    "zarya": {"Particle Barrier": "10s/2ch", "Projected Barrier": "shared", "Graviton Surge": "ULT"},
    "zenyatta": {"Orb of Discord": "no CD", "Orb of Harmony": "no CD", "Transcendence": "ULT"},
}

HERO_PLAY = {
    "ana": "スリープはダイブ着地まで残す。グレはタンクの足下。高所の奥に立ち、前に出ない。",
    "ashe": "ダイナマイトを盾の裏と空に当てる。コーチガンは近接用に残す（10秒）。",
    "baptiste": "ランプ25秒はファイト前に温める。高所からヒットスキャン。",
    "brigitte": "フランカーに鞭4秒を振る。盾で前に出すぎない。",
    "cassidy": "マググレ10秒をダイバーに。中距離の箱から出ない。",
    "dva": "マトリックスを爆弾とバレッジに残す。ブースター3.5秒でバックラインへ。",
    "doomfist": "ブロックでチャージしてからパンチ。ハックとスリープが来たら潜る。",
    "genji": "ディフレクト8秒をウルトとグレに。ダッシュはキルリセット。",
    "kiriko": "鈴14秒をアンチとスタンに残す。TP7秒で危険なサポへ。",
    "lucio": "アンプ12秒を突入に合わせる。壁で視線を切る。",
    "mercy": "リザ30秒。GAで高所循環。ダメージブースト対象を固定しすぎない。",
    "moira": "フェード6秒をフックとスリープの後に。オーブは壁に当てて往復。",
    "orisa": "ジャベリン6秒でダイブを止める。フォルティファイ中に前に出る。",
    "pharah": "コンカッシブ7秒で距離。ヒットスキャンの死角（頭上やや後ろ）にいる。",
    "reaper": "レイス8秒は入る前ではなく帰る時。タンクの足元。",
    "reinhardt": "チャージ7秒を通路の外で撃たない。ファイア6秒でポーク。",
    "roadhog": "フック8秒をサポに。ブレス8秒をファイト中に使う。",
    "sigma": "グラスプ12秒をグレと爆弾に。岩10秒でダイブを落とす。",
    "sombra": "ハック4秒をダイブタンクとバスティオンに。トランス6秒を先に置く。",
    "tracer": "ブリンクを2つ残して入る。リコール12秒が戻る手段。",
    "widowmaker": "グラップル12秒を逃げる用に残す。位置を毎回変える。",
    "winston": "ジャンプ5秒でサポへ。バブル13秒を着地に置く。",
    "zarya": "バブルをダイブのバーストに合わせる。低チャージなら前に出ない。",
    "zenyatta": "ディスコードをタンクに固定。トランスをバレッジとブレードに残す。",
    "soldier-76": "ヘリックス6秒を近接に。フィールド15秒をファイト地点へ。",
    "sojourn": "スライド7秒で高所。レールはヘッド。",
    "hanzo": "ソニック12秒を角の先へ。ストーム10秒で近接を払う。",
    "junkrat": "マインで高所とブープ。罠は側面。",
    "mei": "壁12秒でダイブを分断。クライオはフック後。",
    "bastion": "変形は人数が揃ってから。グレ8秒を角に。",
    "mauga": "オーバードライブ12秒中に殴る。ケージは1vs1。",
    "ramattra": "ネメシス8秒を近接地点で。ボルテックスで空を落とす。",
    "junker-queen": "シャウト11秒で着地。ナイフでサポを抜く。",
    "illari": "パイロンは壊される前提で高所奥。アウトバースト7秒で離脱。",
    "lifeweaver": "グリップ19秒はダイブ対象へ。花台で高所を作る。",
    "juno": "リング14秒を突入に。本体は極めて脆いので高所循環。",
    "echo": "フライト6秒で高所。ビームは低体力に。",
    "venture": "バロウ8秒でバンカーへ。地上にいる時間を短く。",
    "dmon": "水平ダッシュで距離を詰める。空には届かないのでヒットスキャンと組む。",
    "domina": "長射程ビームは視線のある地点。側面ダイブに崩壊するので壁を背に。",
    "hazard": "ウォールで分断。リープはアンチの後。",
    "wrecking-ball": "ハックされたら転がって逃げる。パイル10秒をポイントに。",
    "mizuki": "鎖で空を落とす。攻撃しすぎて死なない。",
    "wuyang": "タイダル12秒でダイブを返す。",
    "jetpack-cat": "空はヒットスキャンの的。運搬は安全な時だけ。",
    "freja": "ダッシュでエイムを更新。近接には距離。",
    "vendetta": "近接なので視線の折れで戦う。",
    "shion": "バイクで側面。CCに当たったら終わり。",
    "sierra": "ドローンで高所。至近は弱い。",
    "emre": "ソルジャー寄りの安定。アルティメットの飛行で空を見る。",
    "anran": "炎の突進はCC待ち。死んでもウルトに注意。",
    "symmetra": "TPを側面に。ビームは盾とD.Vaに。",
    "torbjorn": "タレットは側面監視。本線に置かない。",
}
